### ISSUE TITLE
Bootloader ?

### ISSUE THREAD

**Issue by plapointe6** [Arc13/Pyrus#2]
Hello,

I successfully compiled the code and flashed the app and the softdevice to my PineTime. However, the app won't run and constantly reboot.

Can you please point me to the bootloader you used with your PineTime ? I am pretty sure that my bootloader causes me troubles. 

Thanks for your work!

**Comment by Kuruyia** [comment]
Hi!

If you cloned the repo without any modification to the code, I'd recommend you first to change [L23 in Application.h](https://github.com/Kuruyia/Pyrus/blob/master/src/Application.h) from `Platform::Nrf52Dk` to `Platform::PineTime` (change the #include accordingly).
That'll certainly allow you to run it on the actual PineTime instead of an nRF52 DK (which I use for developing), although I didn't test it for a long time.

I'm not using any bootloader, the nRF52 SDK and SoftDevice are the only external deps that are required.

And lastly, I wouldn't recommend you to use this firmware for anything more than playing with the code/nRF SDK. It has barely anything worth trying and I unfortunately don't have a lot of free time for developing it.

**Comment by plapointe6** [comment]
I use this repo to get me started developing on the PineTime with the NRF5x DK as a lot of work has already been done supporting the PineTime :)

I made the suggested change, now I can see the Pyrus BLE device with nrf connect, but the screen is black and I am unable to connect to it. Now it's clear to me that my life will be really hard without a J-link (I only have a ST-Link for now). There is some hardcoded GPIO numbers in Application.cpp, so I will check this to ensure they match the PineTime.

Anyway, thanks !

**Comment by Kuruyia** [comment]
Np, good luck and have fun ^^
